// Generated by CoffeeScript 1.10.0
(function() {
  var $generate;

  $generate = document.getElementById('generate');

  $generate.onclick = function() {
    return console.log('Clicked the button!');
  };

}).call(this);

//# sourceMappingURL=app.js.map
